language: bash

before_script:
    - curl -L "https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz" | tar zx
    - validationOutput=$(curl http://online.swagger.io/validator/debug?url=http://petstore.swagger.io/v2/swagger.json)

script:
    - bash api-spec_validation_test.sh
