language: bash

before_script:
  - curl -L "https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz" | tar zx

script:
  # Get proper branch name based on http://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  # Now prepare the open API spec file to use the online validator service - http://online.swagger.io/validator/debug?url=
  - export OPEN_API_SPEC_FILE=https://raw.githubusercontent.com/amardeshbd/medium-api-specification/feature/add_travis_ci_build/medium-api-specification.yaml
  # Show in console what are the test values
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - echo "OpenAPI Specification File=$OPEN_API_SPEC_FILE"
  # All variables ready - run the test script
  - bash api-spec_validation_test.sh
