swagger: "2.0"
info:
  description: |
    Medium’s unofficial API documentation using OpenAPI specification.

    [Original API document](https://github.com/Medium/medium-api-docs) can also be viewed for most up to date API spec.


  version: "1.0.0"
  title: Medium.com - Unofficial API Spec
  termsOfService: https://medium.com/@feerst/2b405a832a2f
  contact:
    name: https://medium.com/developers/about
host: api.medium.com
basePath: /v1
schemes:
  - https
paths:
  /me:
    get:
      tags:
        - user
      summary: User details
      description: Getting the authenticated user's details
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/UserResponse"
        401:
          description: The `accessToken` is invalid or has been revoked.
        
  /users/{userId}/publication:
    get:
      summary: User's publications
      description: Returns a full list of publications that the user is related to in some way. This includes all publications the user is subscribed to, writes to, or edits.
      tags:
        - Publication
      parameters:
        - in: path
          name: userId
          description: A unique identifier for the user.
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/PublicationResponse"
        401:
          description: The `accessToken` is invalid, lacks the `listPublications` scope or has been revoked.
        403:
          description: The request attempts to list publications for another user.
        
  /publications/{publicationId}/contributors:
    get:
      summary: Contributors of Publication
      description: This endpoint returns a list of contributors for a given publication. In other words, a list of Medium users who are allowed to publish under a publication, as well as a description of their exact role in the publication (for now, either an editor or a writer).
      parameters:
        - in: path
          name: publicationId
          description: A unique identifier for the publication.
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#definitions/ContibutorResponse"
    
        

      
definitions:
  UserResponse:
    type: object
    title: User Container
    description: Container object for user info
    properties:
      data:
        $ref: "#/definitions/User"
  User:
    type: object
    properties:
      id:
        type: string
        description: A unique identifier for the user.
      username:
        type: string
        description: The user’s username on Medium.
      name:
        type: string
        description: The user’s name on Medium.
      url:
        type: string
        description: The URL to the user’s profile on Medium
      imageUrl:
        type: string
        description: The URL to the user’s avatar on Medium
  
  
  PublicationResponse:
    title: Publication List Container
    description: Container object for publication list.
    properties: 
      data:
        type: array
        items:
          $ref: "#/definitions/Publication"
  
  Publication:
    type: object
    title: Publication Info
    description: Publications provide a way for authors to work collaboratively within a common narrative framework, brand or point of view.
    properties:
      id:
        type: string
        description: A unique identifier for the publication.
      name:
        type: string
        description: The publication’s name on Medium.
      description:
        type: string
        description: Short description of the publication
      url:
        type: string
        description: The URL to the publication’s homepage
      imageUrl:
        type: string
        description: The URL to the publication’s image/logo
        

  ContibutorResponse:
    title: Contributors list for a publication
    description: list of contributors for a given publication
    properties: 
      data:
        type: array
        items:
          $ref: "#/definitions/Contibutor"
          
  Contibutor:
    type: object
    title: Contributor
    description: Contibutor 
    properties:
      publicationId:
        type: string
        description: An ID for the publication. This can be lifted from response of publications above
      userId:
        type: string
        description: A user ID of the contributor.
      role:
        type: string
        description: Role of the user identified by userId in the publication identified by `publicationId`. *editor* or *writer*




        