# This is a basic workflow to validate swagger spec

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Validate Swagger and OpenAPI using Swagger CLI
        uses: mbowman100/swagger-validator-action@1.3
        with:
          # Swagger/OpenAPI file(s) to validate
          # https://github.com/marketplace/actions/validate-swagger-and-openapi-using-swagger-cli
          files: medium-api-specification.yaml
